---
name: Run PR checks

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Our linter configuration files will be specified relative to the root of the workspace
          # (/) rather than within the default directory (.github/linters)
          LINTER_RULES_PATH: /
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          YAML_CONFIG_FILE: .yamllint.yaml
          # A specific subset of linters are enabled
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          # Ideally, we should validate only changed files; we don't want to have a
          # PR fail because rules changed outside the PR itself.
          VALIDATE_ALL_CODEBASE: false
          # The possum is fun but it does add a little noise to the workflow
          SUPPRESS_POSSUM: true
