---
# This is a basic workflow to help you get started with Actions

name: Run PR checks
# Controls when the workflow will run
# yamllint disable-line rule:truthy
on:
  # Triggers the workflow on push events for the develop branch
  # and on every PR
  push:
    branches:
      - develop
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    name: Lint code base
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Our linter configuration files will be specified relative to the root of the workspace
          # (/) rather than within the default directory (.github/linters)
          LINTER_RULES_PATH: /
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          YAML_CONFIG_FILE: .yamllint.yaml
          # A specific subset of linters are enabled
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          # Ideally, we should validate only changed files; we don't want to have a
          # PR fail because rules changed outside the PR itself.
          VALIDATE_ALL_CODEBASE: false
          # The possum is fun but it does add a little noise to the workflow
          SUPPRESS_POSSUM: true
