---
# This is a basic workflow to help you get started with Actions

name: Run PR checks
# Controls when the workflow will run
# yamllint disable-line rule:truthy
on:
  # Triggers the workflow on push events for the develop branch
  # and on every PR
  push:
    branches:
      - develop
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    name: Lint code base
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: lint.yaml
